# Generated by Django 5.2.8 on 2025-11-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_of_birth'),
        ('users', '0004_create_superuser'),
    ]

    operations = [
    ]
