# Generated by Django 5.2.8 on 2025-11-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_verified_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
